name: Build MacOS Binary

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Récupération du projet
      uses: actions/checkout@v4

    - name: Installer Python 3.9.1
      uses: actions/setup-python@v5
      with:
        python-version: 3.9.1

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Créer le binaire Mac
      run: |
        pyinstaller --onefile rower_bridge_FTMS.py

    - name: Sauvegarder le binaire
      uses: actions/upload-artifact@v4
      with:
        name: rower_bridge_macos
        path: dist/rower_bridge_FTMS
